version: '3'
services:
    customer-service:
        container_name: customer-service
        image: rizahorasan/customer-service-image
        restart: always
        ports: 
            - 6006:8001
        environment: 
            WAIT_HOSTS: mysql:3306
        depends_on: 
            - simple-docker-mysql-2
    simple-docker-mysql-2:
        container_name: simple-docker-mysql-2
        image: mysql
        environment: 
            MYSQL_DATABASE: sampledb
            MYSQL_ROOT_PASSWORD: passworddb
            MYSQL_ROOT_HOST: '%'
        ports:
            - 3306:3306
        volumes:
            - ./sql_init:/docker-entrypoint-initdb.d        
